version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: iot_fuzzer_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto_config:/mosquitto/config

  backend:
    build: ./backend
    container_name: iot_fuzzer_engine
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto

  frontend:
    build: ./frontend
    container_name: iot_fuzzer_ui
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src